databases:
  - name: blogsitedb
    plan: free
    databaseName: blogsite
    user: blogsiteuser

services:
  - type: web
    plan: free
    name: blogsite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn website.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blogstiedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4