# Generated by Django 5.1.4 on 2024-12-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.JSONField(blank=True, null=True, verbose_name='tags'),
        ),
    ]
