# Generated by Django 5.1 on 2024-12-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.JSONField(blank=True, verbose_name='tags of the blog'),
        ),
    ]
